### ISSUE TITLE
Cannot open repository due to "malformed e-mail"

### ISSUE THREAD

**Issue by hagward** [git-up/GitUp#111]
When trying to open a specific repository, I'm met with a dialog with the message:

> Failed to parse signature - malformed e-mail

I am not sure which signatures it is trying to parse, but looking at all the email addresses in the repository (using the command `git log --format='%ae' | sort -u`) I find a few funny-looking ones:

- (empty line)
- `<firstname.lastname@domain.com`
- `name@domain.(com)`
- `´firstname.lastname@domain.com´`

**Comment by swisspol** [comment]
What's the entire message in the alert dialog?

**Comment by hagward** [comment]
That is the entire message. When googling for the error message I found [this issue in libgit2](https://github.com/libgit2/libgit2sharp/issues/435) however, so maybe this is an issue that should be filed in that project instead?

<img width="426" alt="screen shot 2016-04-07 at 17 08 58" src="https://cloud.githubusercontent.com/assets/130045/14356061/9d20be3e-fce3-11e5-86bc-0c1659092c3e.png">

**Comment by swisspol** [comment]
It's certainly coming out of ligbit2 upon which GitUp is built, rather than GitUp. To trace down this error though and report it with enough information to libgit2, you would need to build GitUp locally, put a breakpoint on `static int signature_error(const char *msg)` (search in Xcode) and run it.

Is this repo public by any chance?

**Comment by hagward** [comment]
I see, thanks for the information! I'm unsure if I'll be able to do this though, as I don't have any experience with Objective-C and only use Mac at work. If I cannot get it up and running in Windows that is?

Regarding the repository, it is unfortunately not public, but I'll try and see if I can conjure up a new one that triggers the same error.

**Comment by swisspol** [comment]
GitUp is OS X only.

Looks like you have some invalid emails in your repo anyway, but knowing which ones trips libgit2 would require debugging. Then a bug report can be filled with them.

I'm closing this task since this is a not GitUp issue, but feel free to add a comment if you can create a repro case and I'll file a bug with libgit2.
