### ISSUE TITLE
Can't checkout branch

### ISSUE THREAD

**Issue by NikKovIos** [git-up/GitUp#279]
Steps:

0) There is base branch (`A`)
1)  Create a branch (`B`) from `A`. Checkout it. Add commit and push. 
2) Go to web interface, create merge request from pushed branch (`B`) and accept it.
3) Go back to GitUp and try to checkout branch A.  
It still will be `Not at any branch`

**Comment by swisspol** [comment]
> It still will be `Not at any branch`

This doesn't make sense to me: what do you mean "still". In the workflow you describe, assuming you do steps 0 and 1 from GitUp (or Git for that matter), you will always be on a branch.

Can you provide more details in the steps because it looks like something important is missing? Checkout definitly works in GitUp 😉

**Comment by NikKovIos** [comment]
Oh, i mean still - when you tap on 'HEAD' word while trying to switch to the branch A.

**Comment by swisspol** [comment]
If you see "Not at any branch", it just means you checked out a commit vs a branch. Make sure you double-click on a branch label.
