### ISSUE TITLE
Dark line in the git graph - What does this line mean?

### ISSUE THREAD

**Issue by danielphillips** [git-up/GitUp#317]
I had a branch and pushed it. Another developer made a commit and pushed. I made a commit and then pulled. So I got the choice... Merge or fast forward/rebase. So I chose to fast forward, now I have a funny looking line in-between two commits.

Now if I rebase this branch with develop, the commits up until the line don't move so I end up with my branch partially rebased. What does this dark line mean?

![screen shot 2017-06-01 at 15 25 10](https://cloud.githubusercontent.com/assets/668437/26684338/93a51350-46de-11e7-8a82-2c9e0e501055.png)

![screen shot 2017-06-01 at 15 25 30](https://cloud.githubusercontent.com/assets/668437/26684337/93932262-46de-11e7-8083-16199ccec6e1.png)

**Comment by swisspol** [comment]
I have no idea as I have never seen this before. I don't think it's a rendering bug since you're reporting rebasing is not working as expected around this area anyway.

If you run `git show-ref` in the command line and then see if the SHA1 of either of these 2 commits that make the strange line are in the list, that would be interesting to know.
