### ISSUE TITLE
"Open in Terminal" opens two terminal windows

### ISSUE THREAD

**Issue by rm-code** [git-up/GitUp#369]
Gitup: 1.0.9
Mac OS: 10.13

**Comment by swisspol** [comment]
I can't repro in 10.13.3 with 1.0.9.

**Comment by rm-code** [comment]
@swisspol I still can 😕 Have you tried it with terminal being completely closed (cmd+q)? 

Here's a gif showing how gitup opens two terminal windows in the background. You can see that one is opened "empty" and the other has the appropriate `cd` command.

![gitup](https://user-images.githubusercontent.com/11627131/35782499-359c2b7a-09f9-11e8-9431-41cd447cbe23.gif)

**Comment by davidfmiller** [comment]
FWIW this is prolly due to Terminal re-opening the last window that was open before quitting it _in addition to_ the requested window for the repository. For example...

1) Switch to Terminal.app,
2) Close all the windows (⌘+W),
3) *Then* quit Terminal.app
4) Switch to GitUp and select the "Open in Terminal..." menu for a repository.
5) Terminal.app opens and activates as expected: only window window, whose path has been set for the repository in question.

**Comment by swisspol** [comment]
I tried quitting as well, yes.

For reference, here's the implementation in GitUp:
```
- (IBAction)openInTerminal:(id)sender {
  NSString* script = [NSString stringWithFormat:@"tell application \"Terminal\" to do script \"cd \\\"%@\\\"\"", _repository.workingDirectoryPath];
  [[[NSAppleScript alloc] initWithSource:script] executeAndReturnError:NULL];
  [[NSWorkspace sharedWorkspace] launchApplication:@"Terminal"];
}
```

IIRC ` [[NSWorkspace sharedWorkspace] launchApplication:@"Terminal"];` is needed to bring Terminal to the front.

**Comment by rm-code** [comment]
@davidfmiller In the gif above I reproduced it with all windows being closed and it definitely doesn't restore any of my previously open windows.

Might be some weird setting on my end though if both of you can't reproduce.
