### ISSUE TITLE
Is it possible to save credentials?

### ISSUE THREAD

**Issue by Briahas** [git-up/GitUp#373]
Every time I use push/pull i see this [image](https://monosnap.com/file/FCLMPTwmpcvu1r4ojo2SZMABkPA3yc.png)

Though, SourceTree asked it only ones.

**Comment by fwal** [comment]
Have the same issue, worked before but popped up on High Sierra. Also after filling in the form, gitup freezes, max out the cpu and never finishes...

**Comment by Briahas** [comment]
any updates?

**Comment by swisspol** [comment]
What if you saves the credentials in the command line when prompted by Git CLT? GitUp should be able to read them.

**Comment by swisspol** [comment]
Seems like a dup of #343

**Comment by fwal** [comment]
For me it never asks for keychain access like in #343...

**Comment by fwal** [comment]
Got it to work by doing the following:
1. I checked my keychain and found two internet passwords named "github.com" and removed the oldest of them.
2. On the one that I kept, I added GitUp to the "always allow" access list and saved it
3. I opened GitUp and tried a remote operation
4. This time it asked me if allowed keychain access (instead of the one dialog originally described in this issue)
5. After that it freezed again so I force-quit the program
6. When starting it again everything works, no prompts, no freezes. 🎉🤔

**Comment by Briahas** [comment]
Cant make it works.

Asks credentials every time. 
Though, in Terminal "git pull" doesn't ask for creds.

**Comment by Briahas** [comment]
Any suggestions?

**Comment by danielchasehooper** [comment]
@swisspol I gave @fwal's advice a try and it fixed it for me. seems like gitup could detect multiple keys, or let you know to check for this situation when the keys it gets from keychain access don't work.

**Comment by swisspol** [comment]
Duo of #475

**Comment by NikKovIos** [comment]
Removing all items from keychain with name `gitlab` helped me.

**Comment by igorbarbashin** [comment]
For some reason I couldn't delete github entries from Keychain GUI.
This command helped:
```
git credential-osxkeychain erase
host=github.com
protocol=https
```

Press `enter` twice.

Then try to do `git push` you'll be prompted with username and password. Use your personal access token

Source: https://stackoverflow.com/a/51807090
