### ISSUE TITLE
Make font size selectable

### ISSUE THREAD

**Issue by jwiegley** [git-up/GitUp#470]
I'd love to use this tool, but everything is too tiny to read on my monitor. Is there a way to increase font size by, say, 100%?

**Comment by swisspol** [comment]
No, it’s not possible and there are no plans to change it.

**Comment by jwiegley** [comment]
Ah, too bad, it looks like it would have been a nice tool to use.

**Comment by MrLavender** [comment]
Yes, this is a real shame. GitUp is exactly what I want from a Git GUI but this one issue makes it unusable for me. The font is seriously tiny by any standard, and while I can read it it's not comfortable for extended use.

Just allowing it to be configured for the diff text in the commit view would make all the difference, since that's what I'm looking at most of the time. Even the standard git gui client allows this.

**Comment by donraj** [comment]
Can we have the option to change font size please? On big monitors its not really usable.

**Comment by douglashill** [comment]
I've implemented a text size setting in my fork: https://github.com/douglashill/GitUp/releases

**Comment by comatory** [comment]
Wish at least the diff view would be configurable.

**Comment by mluisbrown** [comment]
I created a PR for this: https://github.com/git-up/GitUp/pull/2727
