### ISSUE TITLE
Signing commits

### ISSUE THREAD

**Issue by emarashliev** [git-up/GitUp#527]
Is not possible to sign the commits although did execute `git config --global commit.gpgsign true`. For the command line client it work but no for GitUp.

**Comment by lucasderraugh** [comment]
If it works correctly in the CLI but not the GUI, it would be nice to know why that is. Open to a PR on it!

**Comment by rye** [comment]
This is because GitUp does not shell out to Git; instead it uses libgit2 to interact with the repository. Libgit2 has (by intention) no dependencies, so interaction with GPG must be done entirely in userspace, either through library bindings or shelling out to GPG. In either case, this support would need to be hand-coded.

Even a cursory search of the Issues for this project would have shown that this has been mentioned/requested multiple times before. See #42.

**Comment by lucasderraugh** [comment]
Let’s close this issue as we already are tracking it with #42
