### ISSUE TITLE
Auto update doesn't work (continuous channel)

### ISSUE THREAD

**Issue by vhbit** [git-up/GitUp#544]
I have 1.0.11 (1027) installed with continuous update channel. For a couple of days every time I start `GitUp` I get a notification that I should relaunch to get updated to 1.1 (1029) but it seems relaunch doesn't help. 

When I open "About" instead of version I see a label "Update pending".

**Comment by lucasderraugh** [comment]
Ya, this was my bad. I'm waiting on @swisspol to return so he can add me to his development team. It's failing right now to unpack the version I signed because it doesn't match the version on disk. I'm hoping to resolve this ASAP. In the meantime you can switch to Release channel if it's super annoying. Sorry for the inconvenience!

I'll close this issue out when it's resolved.

**Comment by lucasderraugh** [comment]
I just got the certificates and it should be good to download. Let me know if it goes smoothly for you. Feel free to close this issue if it's resolved. Thanks!

**Comment by vhbit** [comment]
@lucasderraugh indeed, it works now, thanks!
