### ISSUE TITLE
Open Recent has no entries

### ISSUE THREAD

**Issue by johncoxon** [git-up/GitUp#58]
At some point since I started using GitUp, the Open Recent submenu has stopped populating with recently opened repos (it just permanently has a greyed out 'Clear Menu'), such that I have to use ⌘O to open any repo I want to get to.

I'm running GitUp 1.0.4 (1012) on OS X 10.11.3.

**Comment by swisspol** [comment]
GitUp uses NSDocument and the Cocoa manages this menu, not GitUp. The recent list in the welcome window is displayed by GitUp but the content still comes from Cocoa:

![image](https://cloud.githubusercontent.com/assets/627915/13498912/c4d4de0e-e110-11e5-8517-c4143f48c277.png)

This doesn't sound a like the root cause is in GitUp. Maybe you've changed this System Preferences setting?

![image](https://cloud.githubusercontent.com/assets/627915/13498862/87c8d1be-e110-11e5-9e71-d3fb0595a1a0.png)

**Comment by sesam** [comment]
I have the Recently Opened... menu empty. Some months ago, it used to be populated or empty, randomly. In the last month or so, I think it has never had any entries.

And the System Preferences setting was at None. I don't think I've ever changed it, but maybe there was an OS update that made this change. Maybe instead of a bug, a feature request, to explain this in-app? I'm on Mac since many years, and had no idea about this. Probably obvious for all who developed their own Mac apps, but maybe not to many more folks :)

**Comment by sesam** [comment]
The System Preferences setting didn't make a difference yet. Tried opening and closing a few repos, restarting Gitup between, in different combinations, to no effect.
