### ISSUE TITLE
Feature Request: Open in tab

### ISSUE THREAD

**Issue by ppo** [git-up/GitUp#721]
Add a menu `File › Open in tab…`

**Comment by mdznr** [comment]
What would be opened in a new tab?

**Comment by lapfelix** [comment]
Maybe it could be a global setting where every opened repository would go in a new tab instead of a window.

**Comment by mdznr** [comment]
This already exists:
1. System Preferences > General > Prefer tabs
2. Hold Option when a new window (or tab) opens and it will temporarily invert your window tabbing preference (good for one-off cases)
3. Override this for any standard macOS app. For example, for GitUp: `defaults write co.gitup.mac AppleWindowTabbingMode "always"`

**Comment by ppo** [comment]
Thanks @mdznr, but…

1. I don't see that in the System Preferences (on macOS Catalina 10.15.7).
2. It doesn't work. I hold Option all along from before clicking on the menu `File › Open` until the repo opens.
3. I prefer the default to be "open in new window".

**Comment by mdznr** [comment]
1. I think it used to be in Dock presences before Big Sur.
2. This should almost certainly work. AppKit checks for the Option key while opening new windows and opens them as tabs instead, if another tab-able window is available on the current space.

**Comment by ppo** [comment]
1. Yes. Anyway, I don't want to change that globally.
2. Well, it doesn't work for me with GitUp 1.1.3 (when doing what I explained).
With the `File` menu open, when I hold the Option key, I see the `Close` changing into `Close All` but nothing else. Should I see a change in the `Open` option?

**Comment by mdznr** [comment]
2. Not all the menu items that open windows will change their titles to reflect the change in system windowing behavior. I’ve been testing this functionality the past day and haven’t been able to get it **not** to work.

**Comment by ppo** [comment]
Thanks @mdznr . It's maybe a problem on my install only.

I'm using GitUp 1.1.3 (1036) on macOS Catalina 10.15.7 (19H15).  
With System Preferences › Dock › Prefer tabs when opening documents: In Full Screen Only.

**Comment by mdznr** [comment]
I haven’t heard of any other reports of this kind of functionality not working in standard macOS apps. Are you sure we’re referring to the exact same behavior? Here are my steps to reproduce:

Set up:
0. Set preference to prefer tabs “in full screen”

1. Open GitUp
2. File > Open
3. Select any repo from the menu
4. See window appear (not in full-screen)
At this point, there’s no difference between opening as a window and as a tab because there aren’t any other windows open to tab with
5. File > Open
6. Press Option key down
7. Select another repo from the menu
8. See window appear as tab with the window opened in step 4
9. Release holding the Option key

**Comment by ppo** [comment]
@mdznr That's exactly what I'm doing… and no, it's not working for me.

PS: Thanks for the #9 🤣

**Comment by ppo** [comment]
Funny thing is that it works when I open a repo from the `Open Recent` menu.
